name: GO CI
on: push
jobs:

  Clone:
    runs-on: ubuntu-latest
    steps:
      - name: clone-down
        uses: actions/checkout@v2
      - name: Upload backend
        uses: actions/upload-artifact@v2
        with: 
          name: backend
          path: backend
      - name: Upload frontend
        uses: actions/upload-artifact@v2
        with: 
          name: frontend
          path: frontend

  Build_backend:
    runs-on: ubuntu-latest
    needs: [Clone]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.16.4’
      - name: retrive backend
        uses: actions/download-artifact@v2
        with: 
          name: backend
          path: .
      - name: Build backend
        run: go build .

  Build_frontend:
    runs-on: ubuntu-latest
    needs: [Clone]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.16.4’
      - name: retrive frontend
        uses: actions/download-artifact@v2
        with: 
          name: frontend
          path: .
      - name: Build frontend
        run: go build .
  
