name: GO CI
on: push
jobs:

  Clone:
    runs-on: ubuntu-latest
    steps:
      - name: clone-down
        uses: actions/checkout@v2
      - name: Upload backend
        uses: actions/upload-artifact@v2
        with: 
          name: backend
          path: backend
      - name: Upload frontend
        uses: actions/upload-artifact@v2
        with: 
          name: frontend
          path: frontend

  Build_backend:
    runs-on: ubuntu-latest
    needs: [Clone]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - name: retrive backend
        uses: actions/download-artifact@v2
        with: 
          name: backend
          path: .
      - name: Build backend
        run: go build .
      - name: Upload backend_build
        uses: actions/upload-artifact@v2
        with: 
          name: backend_build
          path: .

  Build_frontend:
    runs-on: ubuntu-latest
    needs: [Clone]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - name: retrive frontend
        uses: actions/download-artifact@v2
        with: 
          name: frontend
          path: .
      - name: Build frontend
        run: go build .
      - name: Upload frontend_build
        uses: actions/upload-artifact@v2
        with: 
          name: frontend_build
          path: .
    
  Frontend_pre_test:
    runs-on: ubuntu-latest
    needs: [Build_frontend]
    steps:
      - name: Retrive frontend_build
        uses: actions/download-artifact@v2
        with: 
          name: frontend_build
          path: .
      - name: Test
        run: go test util.go main.go main_test.go
  
  Run_both_app:
    runs-on: ubuntu-latest
    needs: [Frontend_pre_test, Build_backend]
    steps:
      - name: Retrive frontend_build
        uses: actions/download-artifact@v2
        with: 
          name: frontend_build
          path: .
      - name: Retrive backend_build
        uses: actions/download-artifact@v2
        with: 
          name: backend_build
          path: .
      - name: redigo dependency
        run: |
          sudo apt install redis-server
          redis-server
      - name: check
        run: ls
      - name: Run backend
        run: go run backend
      - name: Run frontend
        run: go run frontend




  
