name: GO CI
on: 
  push:
    branches:
      - 'main'

jobs:
  Clone:
    runs-on: jedie20
    steps:
      - name: clone-down
        uses: actions/checkout@v2
      - name: spin up
        run: docker-compose up -d
      - name: Test frontend respone
        run: |
          chmod +x shell_tests/demo.sh
          shell_tests/demo.sh
